name: Build, test and dockerize the application
on:
  push:
    branches-ignore:
      - main
jobs:
  build-deploy:
    name: Build and test the app, push to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Run unit tests
        run: mvn -B test --file pom.xml

      - name: build the jar file
        run: |
          mvn clean
          mvn -B package --file pom.xml


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: |
          cd frontend
          cd recommender-frontend
          pwd # make sure we're in the right dir
          npm install
        

      - name: Build frontend
        run: |
          cd frontend
          cd recommender-frontend
          pwd # make sure we're in the right dir
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

        

